apiVersion: v1
kind: Namespace
metadata:
  name: llm-eval
  labels:
    app.kubernetes.io/name: llm-eval
    app.kubernetes.io/version: "0.3.0"
    app.kubernetes.io/component: namespace
    app.kubernetes.io/managed-by: kubectl
  annotations:
    description: "LLM-Eval UI-first evaluation platform namespace"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: llm-eval-quota
  namespace: llm-eval
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "5"
    services: "10"
    secrets: "10"
    configmaps: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: llm-eval-limits
  namespace: llm-eval
spec:
  limits:
    - default:
        cpu: "1"
        memory: "2Gi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      type: Container